#!/bin/bash

#awk '{if(NR>1 && $0!="") print $1,$2,$7,$8/100.}' ../data/coinFitInfo.dat \
#    > coinFit.temp

,database ../data/73cu.db 41 > /dev/null
sqlite3 -column ../data/73cu.db 'select * from coincidences' > coin.temp
grep -v "*" coin.temp | grep -v "?" > coin.dat && rm -f coin.temp
